name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Set up Maven settings.xml
      run: |
        mkdir -p ~/.m2
        echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                    http://maven.apache.org/xsd/settings-1.0.0.xsd">
                <servers>
                  <server>
                    <id>nexus</id>
                    <username>${{ secrets.NEXUS_USERNAME }}</username>
                    <password>${{ secrets.NEXUS_PASSWORD }}</password>
                  </server>
                </servers>
              </settings>' > ~/.m2/settings.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Deploy to Nexus
      run: mvn deploy -s ~/.m2/settings.xml
      env:
        MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
